#!/bin/sh

# battery threshold %
threshold=15

# current battery level
battery_path=/sys/class/power_supply/BAT1

[ "$(cat $battery_path/status)" = "Charging" ] && exit
[ "$(cat $battery_path/capacity)" -lt "$threshold" ] &&
    export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus &&
    notify-send -u critical -i /usr/share/icons/Adwaita/32x32/devices/ac-adapter-symbolic.symbolic.png -a "Battery alert" "Battery <= $threshold%"
